contentColumnType: text
fieldGroup: 86069e5c-add0-474a-9b57-cf23b4797b63 # Guitar Page
handle: guitarName
instructions: 'Name of guitar model.'
name: 'Guitar Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
