contentColumnType: string
fieldGroup: 86069e5c-add0-474a-9b57-cf23b4797b63 # Guitar Page
handle: guitarImage
instructions: 'Stock image of guitar.'
name: 'Guitar Image'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:1124c7d3-2cfd-45c6-a33f-1d057c534aff' # Uploads
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add guitar image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1124c7d3-2cfd-45c6-a33f-1d057c534aff' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:1124c7d3-2cfd-45c6-a33f-1d057c534aff' # Uploads
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
